apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-app
  labels:
    app: youtube-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: youtube-app
  template:
    metadata:
      labels:
        app: youtube-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: youtube-app
        image: dhruvdarji123/youtube:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
